version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  persistent:
    volumes:
      - 'odoo_data:/coobytech/odoo-base'

volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
